# Lancement des services
services:

  # Base BD Postgres
  postgres:
    image: postgres:16
    container_name: weather-postgres

    # Variables d'environnement
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weather_db

    # Exposition des ports & volumes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d weather_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # MLFlow
  mlflow:
    image: python:3.11-slim
    container_name: weather-mlflow
    working_dir: /mlflow
    command: >
      sh -c "pip install mlflow psycopg2-binary &&
      python -m mlflow server
      --backend-store-uri postgresql://postgres:admin@postgres:5432/weather_db
      --default-artifact-root /mlflow/mlartifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts '*'
      --cors-allowed-origins '*'"
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow/mlartifacts
    depends_on:
      postgres:
        condition: service_healthy
        
  # API
  api:
    build: .
    container_name: weather-api
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: weather_db
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started
  
  # Service Prometheus  
  prometheus:
    image: prom/prometheus
    container_name: weather-prometheus
    
    # exposition des ports
    ports:
      - "9090:9090"
      
    # volumes
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
  
  # Service Grafana
  grafana:
    image: grafana/grafana
    container_name: weather-grafana
    
    # Exposition des ports
    ports:
      - "3000:3000"
      
    # Variables d'environnement
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    # Sauvegarde des Dashboards
    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prometheus

volumes:
  postgres_data:
  mlflow_artifacts:
  grafana_data:
